// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebook/ent/dialect/entsql"
	"github.com/facebook/ent/dialect/sql/schema"
	"github.com/facebook/ent/schema/field"
)

var (
	// UserColumns holds the columns for the "User" table.
	UserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "money", Type: field.TypeInt64},
		{Name: "meta", Type: field.TypeBytes, SchemaType: map[string]string{"mysql": "JSON", "postgres": "JSON"}},
	}
	// UserTable holds the schema information for the "User" table.
	UserTable = &schema.Table{
		Name:        "User",
		Columns:     UserColumns,
		PrimaryKey:  []*schema.Column{UserColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
		Annotation:  &entsql.Annotation{Table: "User"},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UserTable,
	}
)

func init() {
}
