# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common_v2.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63ommon_v2.proto\x12\x16igloo.customer_account\"T\n\x05Phone\x12\x13\n\x0bphoneNumber\x18\x01 \x01(\t\x12\x1b\n\x13PhoneNationalNumber\x18\x02 \x01(\t\x12\x19\n\x11PhonePrefixNumber\x18\x03 \x01(\t\"*\n\x06IDCard\x12\x0e\n\x06IdType\x18\x01 \x01(\t\x12\x10\n\x08IdNumber\x18\x02 \x01(\t\"\x8a\x03\n\x04User\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x13\n\x0blastLoginAt\x18\x02 \x01(\x03\x12\x0f\n\x07\x63ountry\x18\x03 \x01(\t\x12\x11\n\tfirstName\x18\x04 \x01(\t\x12\x10\n\x08lastName\x18\x05 \x01(\t\x12\r\n\x05\x65mail\x18\x06 \x01(\t\x12\x13\n\x0bphoneNumber\x18\x07 \x01(\t\x12\x13\n\x0b\x65xternal_id\x18\x08 \x01(\t\x12\x19\n\x11PhonePrefixNumber\x18\t \x01(\t\x12\x15\n\rphoneVerified\x18\n \x01(\x08\x12\x0e\n\x06IdType\x18\x0b \x01(\t\x12\x10\n\x08IdNumber\x18\x0c \x01(\t\x12\x12\n\nIdVerified\x18\r \x01(\x08\x12\x0e\n\x06status\x18\x0e \x01(\t\x12\x15\n\remailVerified\x18\x10 \x01(\x08\x12\x10\n\x08language\x18\x11 \x01(\t\x12\x10\n\x08\x66ullName\x18\x12 \x01(\t\x12\r\n\x05title\x18\x13 \x01(\t\x12\x0e\n\x06gender\x18\x14 \x01(\t\x12\x0e\n\x06source\x18\x15 \x01(\t\x12\x0c\n\x04meta\x18\x16 \x01(\x0c\"7\n\x08UserMeta\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\tB9Z7gitlab.com/axinan/backend/common/proto/customer_accountb\x06proto3')



_PHONE = DESCRIPTOR.message_types_by_name['Phone']
_IDCARD = DESCRIPTOR.message_types_by_name['IDCard']
_USER = DESCRIPTOR.message_types_by_name['User']
_USERMETA = DESCRIPTOR.message_types_by_name['UserMeta']
Phone = _reflection.GeneratedProtocolMessageType('Phone', (_message.Message,), {
  'DESCRIPTOR' : _PHONE,
  '__module__' : 'common_v2_pb2'
  # @@protoc_insertion_point(class_scope:igloo.customer_account.Phone)
  })
_sym_db.RegisterMessage(Phone)

IDCard = _reflection.GeneratedProtocolMessageType('IDCard', (_message.Message,), {
  'DESCRIPTOR' : _IDCARD,
  '__module__' : 'common_v2_pb2'
  # @@protoc_insertion_point(class_scope:igloo.customer_account.IDCard)
  })
_sym_db.RegisterMessage(IDCard)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'common_v2_pb2'
  # @@protoc_insertion_point(class_scope:igloo.customer_account.User)
  })
_sym_db.RegisterMessage(User)

UserMeta = _reflection.GeneratedProtocolMessageType('UserMeta', (_message.Message,), {
  'DESCRIPTOR' : _USERMETA,
  '__module__' : 'common_v2_pb2'
  # @@protoc_insertion_point(class_scope:igloo.customer_account.UserMeta)
  })
_sym_db.RegisterMessage(UserMeta)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z7gitlab.com/axinan/backend/common/proto/customer_account'
  _PHONE._serialized_start=43
  _PHONE._serialized_end=127
  _IDCARD._serialized_start=129
  _IDCARD._serialized_end=171
  _USER._serialized_start=174
  _USER._serialized_end=568
  _USERMETA._serialized_start=570
  _USERMETA._serialized_end=625
# @@protoc_insertion_point(module_scope)
