# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import customer_account_v2_pb2 as customer__account__v2__pb2


class CustomerAccountStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateUser = channel.unary_unary(
                '/igloo.customer_account.CustomerAccount/CreateUser',
                request_serializer=customer__account__v2__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=customer__account__v2__pb2.CreateUserResponse.FromString,
                )
        self.UpdateUser = channel.unary_unary(
                '/igloo.customer_account.CustomerAccount/UpdateUser',
                request_serializer=customer__account__v2__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=customer__account__v2__pb2.UpdateUserResponse.FromString,
                )
        self.DeleteUser = channel.unary_unary(
                '/igloo.customer_account.CustomerAccount/DeleteUser',
                request_serializer=customer__account__v2__pb2.DeleteUserRequest.SerializeToString,
                response_deserializer=customer__account__v2__pb2.DeleteUserResponse.FromString,
                )
        self.GetUserByID = channel.unary_unary(
                '/igloo.customer_account.CustomerAccount/GetUserByID',
                request_serializer=customer__account__v2__pb2.GetUserByIDRequest.SerializeToString,
                response_deserializer=customer__account__v2__pb2.GetUserResponse.FromString,
                )
        self.GetUserByExternalID = channel.unary_unary(
                '/igloo.customer_account.CustomerAccount/GetUserByExternalID',
                request_serializer=customer__account__v2__pb2.GetUserByExternalIDRequest.SerializeToString,
                response_deserializer=customer__account__v2__pb2.GetUserResponse.FromString,
                )
        self.GetUserByEmail = channel.unary_unary(
                '/igloo.customer_account.CustomerAccount/GetUserByEmail',
                request_serializer=customer__account__v2__pb2.GetUserByEmailRequest.SerializeToString,
                response_deserializer=customer__account__v2__pb2.GetUserResponse.FromString,
                )
        self.GetUserByPhone = channel.unary_unary(
                '/igloo.customer_account.CustomerAccount/GetUserByPhone',
                request_serializer=customer__account__v2__pb2.GetUserByPhoneRequest.SerializeToString,
                response_deserializer=customer__account__v2__pb2.GetUserResponse.FromString,
                )
        self.GenUserJWTToken = channel.unary_unary(
                '/igloo.customer_account.CustomerAccount/GenUserJWTToken',
                request_serializer=customer__account__v2__pb2.GenUserJWTTokenRequest.SerializeToString,
                response_deserializer=customer__account__v2__pb2.GenUserJWTTokenResponse.FromString,
                )
        self.GetUserMeta = channel.unary_unary(
                '/igloo.customer_account.CustomerAccount/GetUserMeta',
                request_serializer=customer__account__v2__pb2.GetUserMetaRequest.SerializeToString,
                response_deserializer=customer__account__v2__pb2.GetUserMetaResponse.FromString,
                )
        self.SetUserMeta = channel.unary_unary(
                '/igloo.customer_account.CustomerAccount/SetUserMeta',
                request_serializer=customer__account__v2__pb2.SetUserMetaRequest.SerializeToString,
                response_deserializer=customer__account__v2__pb2.EmptyResponse.FromString,
                )
        self.DeleteUserMeta = channel.unary_unary(
                '/igloo.customer_account.CustomerAccount/DeleteUserMeta',
                request_serializer=customer__account__v2__pb2.DeleteUserMetaRequest.SerializeToString,
                response_deserializer=customer__account__v2__pb2.EmptyResponse.FromString,
                )
        self.GetUserFcmToken = channel.unary_unary(
                '/igloo.customer_account.CustomerAccount/GetUserFcmToken',
                request_serializer=customer__account__v2__pb2.GetUserFcmTokenRequest.SerializeToString,
                response_deserializer=customer__account__v2__pb2.GetUserFcmTokenResponse.FromString,
                )


class CustomerAccountServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserByID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserByExternalID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserByEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserByPhone(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenUserJWTToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserMeta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetUserMeta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUserMeta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserFcmToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CustomerAccountServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=customer__account__v2__pb2.CreateUserRequest.FromString,
                    response_serializer=customer__account__v2__pb2.CreateUserResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=customer__account__v2__pb2.UpdateUserRequest.FromString,
                    response_serializer=customer__account__v2__pb2.UpdateUserResponse.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=customer__account__v2__pb2.DeleteUserRequest.FromString,
                    response_serializer=customer__account__v2__pb2.DeleteUserResponse.SerializeToString,
            ),
            'GetUserByID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserByID,
                    request_deserializer=customer__account__v2__pb2.GetUserByIDRequest.FromString,
                    response_serializer=customer__account__v2__pb2.GetUserResponse.SerializeToString,
            ),
            'GetUserByExternalID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserByExternalID,
                    request_deserializer=customer__account__v2__pb2.GetUserByExternalIDRequest.FromString,
                    response_serializer=customer__account__v2__pb2.GetUserResponse.SerializeToString,
            ),
            'GetUserByEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserByEmail,
                    request_deserializer=customer__account__v2__pb2.GetUserByEmailRequest.FromString,
                    response_serializer=customer__account__v2__pb2.GetUserResponse.SerializeToString,
            ),
            'GetUserByPhone': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserByPhone,
                    request_deserializer=customer__account__v2__pb2.GetUserByPhoneRequest.FromString,
                    response_serializer=customer__account__v2__pb2.GetUserResponse.SerializeToString,
            ),
            'GenUserJWTToken': grpc.unary_unary_rpc_method_handler(
                    servicer.GenUserJWTToken,
                    request_deserializer=customer__account__v2__pb2.GenUserJWTTokenRequest.FromString,
                    response_serializer=customer__account__v2__pb2.GenUserJWTTokenResponse.SerializeToString,
            ),
            'GetUserMeta': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserMeta,
                    request_deserializer=customer__account__v2__pb2.GetUserMetaRequest.FromString,
                    response_serializer=customer__account__v2__pb2.GetUserMetaResponse.SerializeToString,
            ),
            'SetUserMeta': grpc.unary_unary_rpc_method_handler(
                    servicer.SetUserMeta,
                    request_deserializer=customer__account__v2__pb2.SetUserMetaRequest.FromString,
                    response_serializer=customer__account__v2__pb2.EmptyResponse.SerializeToString,
            ),
            'DeleteUserMeta': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUserMeta,
                    request_deserializer=customer__account__v2__pb2.DeleteUserMetaRequest.FromString,
                    response_serializer=customer__account__v2__pb2.EmptyResponse.SerializeToString,
            ),
            'GetUserFcmToken': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserFcmToken,
                    request_deserializer=customer__account__v2__pb2.GetUserFcmTokenRequest.FromString,
                    response_serializer=customer__account__v2__pb2.GetUserFcmTokenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'igloo.customer_account.CustomerAccount', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CustomerAccount(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/igloo.customer_account.CustomerAccount/CreateUser',
            customer__account__v2__pb2.CreateUserRequest.SerializeToString,
            customer__account__v2__pb2.CreateUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/igloo.customer_account.CustomerAccount/UpdateUser',
            customer__account__v2__pb2.UpdateUserRequest.SerializeToString,
            customer__account__v2__pb2.UpdateUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/igloo.customer_account.CustomerAccount/DeleteUser',
            customer__account__v2__pb2.DeleteUserRequest.SerializeToString,
            customer__account__v2__pb2.DeleteUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserByID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/igloo.customer_account.CustomerAccount/GetUserByID',
            customer__account__v2__pb2.GetUserByIDRequest.SerializeToString,
            customer__account__v2__pb2.GetUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserByExternalID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/igloo.customer_account.CustomerAccount/GetUserByExternalID',
            customer__account__v2__pb2.GetUserByExternalIDRequest.SerializeToString,
            customer__account__v2__pb2.GetUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserByEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/igloo.customer_account.CustomerAccount/GetUserByEmail',
            customer__account__v2__pb2.GetUserByEmailRequest.SerializeToString,
            customer__account__v2__pb2.GetUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserByPhone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/igloo.customer_account.CustomerAccount/GetUserByPhone',
            customer__account__v2__pb2.GetUserByPhoneRequest.SerializeToString,
            customer__account__v2__pb2.GetUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenUserJWTToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/igloo.customer_account.CustomerAccount/GenUserJWTToken',
            customer__account__v2__pb2.GenUserJWTTokenRequest.SerializeToString,
            customer__account__v2__pb2.GenUserJWTTokenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/igloo.customer_account.CustomerAccount/GetUserMeta',
            customer__account__v2__pb2.GetUserMetaRequest.SerializeToString,
            customer__account__v2__pb2.GetUserMetaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetUserMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/igloo.customer_account.CustomerAccount/SetUserMeta',
            customer__account__v2__pb2.SetUserMetaRequest.SerializeToString,
            customer__account__v2__pb2.EmptyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteUserMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/igloo.customer_account.CustomerAccount/DeleteUserMeta',
            customer__account__v2__pb2.DeleteUserMetaRequest.SerializeToString,
            customer__account__v2__pb2.EmptyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserFcmToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/igloo.customer_account.CustomerAccount/GetUserFcmToken',
            customer__account__v2__pb2.GetUserFcmTokenRequest.SerializeToString,
            customer__account__v2__pb2.GetUserFcmTokenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
