// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/flametest/test/ent/schema"
	"github.com/flametest/test/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescMoney is the schema descriptor for money field.
	userDescMoney := userFields[1].Descriptor()
	// user.DefaultMoney holds the default value on creation for the money field.
	user.DefaultMoney = userDescMoney.Default.(int64)
}
